<a href="https://colab.research.google.com/github/smrithi94/PGP_ML_SQL_DATA/blob/main/Cinema_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# Installing the libraries with the specified version.
!pip install numpy==1.25.2 pandas==1.5.3 -q --user4

Usage:
  pip3 install [options] <requirement specifier> [package-index-options] ...
  pip3 install [options] -r <requirements file> [package-index-options] ...
  pip3 install [options] [-e] <vcs project url> ...
  pip3 install [options] [-e] <local project path> ...
  pip3 install [options] <archive url/path> ...

no such option: --user4

In [ ]:
# uncomment and run the following lines for Google Colab
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df_movie = pd.read_csv('/content/drive/My Drive/Colab Notebooks/movie.csv')

In [ ]:
'''import os
file_list = os.listdir('/content/drive/My Drive/Colab Notebooks')
print(file_list)'''

['Cinema_Analysis', 'Python_PreWork_Session.ipynb', 'foodhub_order.csv', 'Copy of FoodHubFullCodeSaiSmrithi.ipynb', 'FoodHubFullCodeSaiSmrithi.ipynb', 'FoodHubFullCodeSaiSmrithi.html', 'movie.csv', 'user.csv', 'ratings.csv']

In [ ]:
df_ratings = pd.read_csv('/content/drive/My Drive/Colab Notebooks/ratings.csv')

In [ ]:
df_user = pd.read_csv('/content/drive/My Drive/Colab Notebooks/user.csv')

In [ ]:
df_movie.head()

,movie id,movie title,release date,Action,Adventure,Animation,Childrens,Comedy,Crime,Documentary,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story,1-Jan-95,0,0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye,1-Jan-95,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms,1-Jan-95,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,4,Get Shorty,1-Jan-95,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,Copycat,1-Jan-95,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0

In [ ]:
df_ratings.head()

   user id  movie id  rating  timestamp
0      196       242       3  881250949
1      186       302       3  891717742
2       22       377       1  878887116
3      244        51       2  880606923
4      166       346       1  886397596

In [ ]:
df_user.head()

   user id  age gender  occupation zip code
0        1   24      M  technician    85711
1        2   53      F       other    94043
2        3   23      M      writer    32067
3        4   24      M  technician    43537
4        5   33      F       other    15213

In [ ]:
df_movie.shape

(1680, 21)

In [ ]:
df_ratings.shape

(100000, 4)

In [ ]:
df_user.shape

(943, 5)

In [ ]:
df_movie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1680 entries, 0 to 1679
Data columns (total 21 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   movie id      1680 non-null   int64
 1   movie title   1680 non-null   object
 2   release date  1680 non-null   object
 3   Action        1680 non-null   int64
 4   Adventure     1680 non-null   int64
 5   Animation     1680 non-null   int64
 6   Childrens     1680 non-null   int64
 7   Comedy        1680 non-null   int64
 8   Crime         1680 non-null   int64
 9   Documentary   1680 non-null   int64
 10  Drama         1680 non-null   int64
 11  Fantasy       1680 non-null   int64
 12  Film-Noir     1680 non-null   int64
 13  Horror        1680 non-null   int64
 14  Musical       1680 non-null   int64
 15  Mystery       1680 non-null   int64
 16  Romance       1680 non-null   int64
 17  Sci-Fi        1680 non-null   int64
 18  Thriller      1680 non-null   int64
 19  War           1680 non-null   int64
 20  Western       1680 non-null   int64
dtypes: int64(19), object(2)
memory usage: 275.8+ KB

In [ ]:
df_user.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 943 entries, 0 to 942
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   user id     943 non-null    int64
 1   age         943 non-null    int64
 2   gender      943 non-null    object
 3   occupation  943 non-null    object
 4   zip code    943 non-null    object
dtypes: int64(2), object(3)
memory usage: 37.0+ KB

In [ ]:
df_ratings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   user id    100000 non-null  int64
 1   movie id   100000 non-null  int64
 2   rating     100000 non-null  int64
 3   timestamp  100000 non-null  int64
dtypes: int64(4)
memory usage: 3.1 MB

In [ ]:
df_movie.columns

Index(['movie id', 'movie title', 'release date', 'Action', 'Adventure',
       'Animation', 'Childrens', 'Comedy', 'Crime', 'Documentary', 'Drama',
       'Fantasy', 'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance',
       'Sci-Fi', 'Thriller', 'War', 'Western'],
      dtype='object')

In [ ]:
genres =['Action', 'Adventure',
       'Animation', 'Childrens', 'Comedy', 'Crime', 'Documentary', 'Drama',
       'Fantasy', 'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance',
       'Sci-Fi', 'Thriller', 'War', 'Western']

In [ ]:
len(genres)

18

In [ ]:
df_movie[genres].sum().sort_values(ascending=False)

Drama          725
Comedy         505
Thriller       251
Action         251
Romance        247
Adventure      135
Childrens      122
Crime          109
Sci-Fi         101
Horror          92
War             71
Mystery         61
Musical         56
Documentary     50
Animation       42
Western         27
Film-Noir       24
Fantasy         22
dtype: int64

In [ ]:
 df_movie['number_of_genres'] = df_movie.loc[:, genres].sum(axis=1)

In [ ]:
df_movie[df_movie['number_of_genres'] > 1]

,movie id,movie title,release date,Action,Adventure,Animation,Childrens,Comedy,Crime,Documentary,...,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western,number_of_genres
0,1,Toy Story,1-Jan-95,0,0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,3
1,2,GoldenEye,1-Jan-95,1,1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,3
3,4,Get Shorty,1-Jan-95,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,3
4,5,Copycat,1-Jan-95,0,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,3
6,7,Twelve Monkeys,1-Jan-95,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1666,1669,MURDER and murder,20-Jun-97,0,0,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,3
1667,1670,Tainted,1-Feb-98,0,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,2
1670,1673,Mirage,1-Jan-95,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,2
1676,1679,B. Monkey,6-Feb-98,0,0,0,0,0,0,0,...,0,0,0,0,1,0,1,0,0,2
1677,1680,Sliding Doors,1-Jan-98,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,2

In [ ]:
df_movie["Number of Genres"] = df_movie.loc[:, genres].sum(axis=1)

In [ ]:
df_movie["Number of Genres"] = df_movie.iloc[:, 3:].sum(axis=1)

In [ ]:
df_movie

,movie id,movie title,release date,Action,Adventure,Animation,Childrens,Comedy,Crime,Documentary,...,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western,number_of_genres,Number of Genres
0,1,Toy Story,1-Jan-95,0,0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,3,9
1,2,GoldenEye,1-Jan-95,1,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,3,9
2,3,Four Rooms,1-Jan-95,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,3
3,4,Get Shorty,1-Jan-95,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,3,9
4,5,Copycat,1-Jan-95,0,0,0,0,0,1,0,...,0,0,0,0,0,1,0,0,3,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1675,1678,Mat' i syn,6-Feb-98,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,3
1676,1679,B. Monkey,6-Feb-98,0,0,0,0,0,0,0,...,0,0,0,1,0,1,0,0,2,6
1677,1680,Sliding Doors,1-Jan-98,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,2,6
1678,1681,You So Crazy,1-Jan-94,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,3
1679,1682,Scream of Stone (Schrei aus Stein),8-Mar-96,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,3

In [ ]:
df_ratings.head()

   user id  movie id  rating  timestamp
0      196       242       3  881250949
1      186       302       3  891717742
2       22       377       1  878887116
3      244        51       2  880606923
4      166       346       1  886397596

In [ ]:
df_user.head()

   user id  age gender  occupation zip code
0        1   24      M  technician    85711
1        2   53      F       other    94043
2        3   23      M      writer    32067
3        4   24      M  technician    43537
4        5   33      F       other    15213

In [ ]:
#Finding which Genres are liked by which users.

In [ ]:
df_merge = df_movie.merge(df_ratings, on = 'movie id', how = 'inner')

In [ ]:
df_merge

,movie id,movie title,release date,Action,Adventure,Animation,Childrens,Comedy,Crime,Documentary,...,Romance,Sci-Fi,Thriller,War,Western,number_of_genres,Number of Genres,user id,rating,timestamp
0,1,Toy Story,1-Jan-95,0,0,1,1,1,0,0,...,0,0,0,0,0,3,9,308,4,887736532
1,1,Toy Story,1-Jan-95,0,0,1,1,1,0,0,...,0,0,0,0,0,3,9,287,5,875334088
2,1,Toy Story,1-Jan-95,0,0,1,1,1,0,0,...,0,0,0,0,0,3,9,148,4,877019411
3,1,Toy Story,1-Jan-95,0,0,1,1,1,0,0,...,0,0,0,0,0,3,9,280,4,891700426
4,1,Toy Story,1-Jan-95,0,0,1,1,1,0,0,...,0,0,0,0,0,3,9,66,3,883601324
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99985,1678,Mat' i syn,6-Feb-98,0,0,0,0,0,0,0,...,0,0,0,0,0,1,3,863,1,889289570
99986,1679,B. Monkey,6-Feb-98,0,0,0,0,0,0,0,...,1,0,1,0,0,2,6,863,3,889289491
99987,1680,Sliding Doors,1-Jan-98,0,0,0,0,0,0,0,...,1,0,0,0,0,2,6,863,2,889289570
99988,1681,You So Crazy,1-Jan-94,0,0,0,0,1,0,0,...,0,0,0,0,0,1,3,896,3,887160722
99989,1682,Scream of Stone (Schrei aus Stein),8-Mar-96,0,0,0,0,0,0,0,...,0,0,0,0,0,1,3,916,3,880845755

In [ ]:
for i in genres:
    print(i,':' , df_merge[df_merge[i]==1].rating.mean())

Action : 3.480245417953027
Adventure : 3.503526503308369
Animation : 3.5766990291262135
Childrens : 3.3532442216652742
Comedy : 3.3940734781442745
Crime : 3.6322780881440098
Documentary : 3.6728232189973613
Drama : 3.6873793708484772
Fantasy : 3.2152366863905324
Film-Noir : 3.9215233698788228
Horror : 3.2903893172841827
Musical : 3.521396851029471
Mystery : 3.63813155386082
Romance : 3.621704948358255
Sci-Fi : 3.5607227022780834
Thriller : 3.5090069495245064
War : 3.815811874866993
Western : 3.6132686084142396